version: 1.0

phases:
    pre_build:
        commands:
            - npm install
    build:
        commands:
            - npm run build

artifacts:
    base_directory: build
    files:
        - '**/*'
