export const loadingMessages = [
	"diffusing error",
	"counting pixels",
	"quantizing colours",
	"floyding steinbergs",
	"hithering and dithering",
	"making a really cool loading spinner",
	"rofling",
	"finding all your base",
	"hosting on http://127.0.0.1:8080",
	'echo "Hello World!"',
	"ERROR: message not found",
	"thinking of a good loading message",
	"$> imagemagick convert -ordered-dither",
];

// from https://stackoverflow.com/questions/2685435/cooler-ascii-spinners/2685827#2685827
export const spinners = [
	"←↖↑↗→↘↓↙",
	"▁▃▄▅▆▇█▇▆▅▄▃",
	"▉▊▋▌▍▎▏▎▍▌▋▊▉",
	"▖▘▝▗",
	"▌▀▐▄",
	"┤┘┴└├┌┬┐",
	"◢◣◤◥",
	"◰◳◲◱",
	"◴◷◶◵",
	"◐◓◑◒",
	"|/-\\",
	".oO@*",
	["◡◡", "⊙⊙", "◠◠"],
	["◜ ", " ◝", " ◞", "◟ "],
	"◇◈◆",
	"⣾⣽⣻⢿⡿⣟⣯⣷",
	"⡀⡁⡂⡃⡄⡅⡆⡇⡈⡉⡊⡋⡌⡍⡎⡏⡐⡑⡒⡓⡔⡕⡖⡗⡘⡙⡚⡛⡜⡝⡞⡟⡠⡡⡢⡣⡤⡥⡦⡧⡨⡩⡪⡫⡬⡭⡮⡯⡰⡱⡲⡳⡴⡵⡶⡷⡸⡹⡺⡻⡼⡽⡾⡿⢀⢁⢂⢃⢄⢅⢆⢇⢈⢉⢊⢋⢌⢍⢎⢏⢐⢑⢒⢓⢔⢕⢖⢗⢘⢙⢚⢛⢜⢝⢞⢟⢠⢡⢢⢣⢤⢥⢦⢧⢨⢩⢪⢫⢬⢭⢮⢯⢰⢱⢲⢳⢴⢵⢶⢷⢸⢹⢺⢻⢼⢽⢾⢿⣀⣁⣂⣃⣄⣅⣆⣇⣈⣉⣊⣋⣌⣍⣎⣏⣐⣑⣒⣓⣔⣕⣖⣗⣘⣙⣚⣛⣜⣝⣞⣟⣠⣡⣢⣣⣤⣥⣦⣧⣨⣩⣪⣫⣬⣭⣮⣯⣰⣱⣲⣳⣴⣵⣶⣷⣸⣹⣺⣻⣼⣽⣾⣿",
	"⠁⠂⠄⡀⢀⠠⠐⠈",
	[">))'>", " >))'>", "  >))'>", "   >))'>", "    >))'>", "   <'((<", "  <'((<", " <'((<"],
	[
		"    /\\O\n     /\\/\n    /\\\n   /  \\\n LOL  LOL",
		"     _O\n   //|_\n    |\n   /|\n   LLOL",
		"      O\n     /_\n     |\\\n    / |\n  LOLLOL",
	],
	[
		`╔════╤╤╤╤════╗\n║    │││ \\   ║\n║    │││  O  ║\n║    OOO     ║`,
		`╔════╤╤╤╤════╗\n║    ││││    ║\n║    ││││    ║\n║    OOOO    ║`,
		`╔════╤╤╤╤════╗\n║   / │││    ║\n║  O  │││    ║\n║     OOO    ║`,
		`╔════╤╤╤╤════╗\n║    ││││    ║\n║    ││││    ║\n║    OOOO    ║`,
	],
];
